"use client";
import { AlertTriangle, CheckCircle2, ScanText, ShieldAlert } from "lucide-react";
import { useMemo, useState } from "react";
import type { ChangeEvent } from "react";
const rules=[
 {label:"Cam kết / đảm bảo tuyệt đối",severity:"Cao",why:"Facebook hạn chế hứa hẹn kết quả tuyệt đối.",words:["cam kết 100","đảm bảo 100","chắc chắn khỏi","trị dứt điểm"]},
 {label:"Nhắm thuộc tính cá nhân",severity:"Cao",why:"Không nên ngụ ý biết tình trạng cá nhân của người xem.",words:["bạn có bị","bạn đang bị","bạn thừa cân","bạn nghèo","bạn ế"]},
 {label:"Sức khỏe / giảm cân",severity:"Cao",why:"Tuyên bố y tế hoặc giảm cân cấp tốc dễ bị từ chối.",words:["giảm cân cấp tốc","chữa khỏi","thần dược","tan mỡ"]},
 {label:"Hứa hẹn tài chính",severity:"Cao",why:"Hứa thu nhập/lợi nhuận là vùng nhạy cảm.",words:["làm giàu","kiếm tiền nhanh","lãi khủng","đổi đời"]},
 {label:"Giật gân / clickbait",severity:"Vừa",why:"Nội dung giật gân làm giảm chất lượng quảng cáo.",words:["sốc","không thể tin","chấn động","bí mật"]},
 {label:"Before / After",severity:"Vừa",why:"Ngôn ngữ trước-sau, đặc biệt về cơ thể, có rủi ro.",words:["trước và sau","before after","hình trước sau"]},
];
export default function AdsPolicyPage(){const [text,setText]=useState("Bạn đang bị thừa cân? Cam kết 100% giảm cân cấp tốc và đổi đời chỉ sau 7 ngày!"); const matches=useMemo(()=>rules.map(r=>({...r,found:r.words.filter(w=>text.toLowerCase().includes(w))})).filter(r=>r.found.length),[text]); const score=Math.max(0,100-matches.reduce((s,r)=>s+(r.severity==="Cao"?22:12),0)); const safer=text.replace(/cam kết 100%/gi,"hướng tới hiệu quả phù hợp").replace(/giảm cân cấp tốc/gi,"xây dựng thói quen lành mạnh").replace(/đổi đời/gi,"cải thiện kỹ năng").replace(/Bạn đang bị thừa cân\?/gi,"Bạn muốn chăm sóc sức khỏe tốt hơn?"); return <div className="adsmeta-feature-page"><header className="adsmeta-feature-title"><div><span className="adsmeta-feature-icon"><ShieldAlert size={18}/></span><div><h1>Kiểm tra chính sách quảng cáo</h1><p>Quét nội dung trước khi tạo quảng cáo; không thay thế quyết định xét duyệt của Meta.</p></div></div><span className={`adsmeta-score ${score>=80?"is-good":score>=55?"is-medium":"is-bad"}`}>{score}/100</span></header><div className="adsmeta-policy-grid"><section className="adsmeta-feature-card"><div className="adsmeta-card-toolbar"><b>Nội dung quảng cáo</b><span>{text.length} ký tự</span></div><textarea className="adsmeta-policy-editor" value={text} onChange={(e: ChangeEvent<HTMLTextAreaElement>)=>setText(e.target.value)}/><div className="adsmeta-policy-footer"><ScanText size={14}/> Hệ thống kiểm tra từ khóa, tuyên bố và cấu trúc câu có rủi ro.</div></section><section className="adsmeta-feature-card"><div className="adsmeta-card-toolbar"><b>Kết quả phân tích</b><span>{matches.length} nhóm cảnh báo</span></div><div className="adsmeta-policy-issues">{!matches.length&&<div className="adsmeta-policy-clean"><CheckCircle2 size={28}/><b>Chưa phát hiện rủi ro nổi bật</b></div>}{matches.map(r=><article key={r.label}><div><AlertTriangle size={15}/><b>{r.label}</b><span>{r.severity}</span></div><p>{r.why}</p><small>Phát hiện: {r.found.join(", ")}</small></article>)}</div></section><section className="adsmeta-feature-card adsmeta-policy-suggestion"><div className="adsmeta-card-toolbar"><b>Gợi ý viết lại an toàn hơn</b></div><p>{safer}</p><button onClick={()=>setText(safer)}>Dùng bản gợi ý</button></section></div></div>}
