import { instantiateTemplateBlocks, resolveTemplatePresetId } from "../editor/template-library";
import { ensureOnlookBlockMeta, createDefaultPageSettings } from "../editor/types";
import { migrateTemplateFlatBlocks, recalculateSectionHeights, CURRENT_EDITOR_SCHEMA_VERSION } from "../editor/core/editor-migration";

export interface SeedTemplateItem {
  template_key: string;
  name: string;
  description: string;
  category: string;
  tags: string[];
  thumbnail_url: string;
  preview_image_url: string;
  editor_data: any;
  is_published: boolean;
  is_featured: boolean;
  price_type: "free" | "pro";
  views_count: number;
  downloads_count: number;
}

const rawMetadata = [
  {
    id: "t1",
    name: "LDP112305 - Theme TikTok Shop Mỹ Phẩm",
    image: "/images/template_cosmetics.png",
    category: "ecommerce",
    isPro: true,
    views: 6120,
    likes: 3120,
    description: "Theme TikTok Shop Mỹ Phẩm với hero ảnh sản phẩm và form tư vấn.",
    tags: ["tiktok", "my-pham", "ecommerce"],
  },
  {
    id: "t2",
    name: "LDP112306 - Thiệp cưới Modern Elegant Wedding",
    image: "/images/template_wedding.png",
    category: "others",
    isPro: true,
    views: 4300,
    likes: 2150,
    description: "Thiệp cưới Modern Elegant phong cách hiện đại và lãng mạn.",
    tags: ["wedding", "thiep-cuoi", "others"],
  },

  {
    id: "t4",
    name: "LDP112308 - Đồng hồ thông minh Smartwatch Pro",
    image: "/images/template_electronics.png",
    category: "ecommerce",
    isPro: true,
    views: 3900,
    likes: 1950,
    description: "Đồng hồ thông minh Smartwatch Pro, tính năng hiện đại.",
    tags: ["smartwatch", "dong-ho", "ecommerce"],
  },
  {
    id: "t5",
    name: "LDP112309 - Spa & Skincare Landing Page",
    image: "/images/template_cosmetics.png",
    category: "service",
    isPro: false,
    views: 4500,
    likes: 2200,
    description: "Spa & Skincare Landing Page giới thiệu dịch vụ làm đẹp cao cấp.",
    tags: ["spa", "skincare", "service"],
  },
  {
    id: "t6",
    name: "LDP112310 - Sự kiện Khai trương cửa hàng",
    image: "/images/template_tea.png",
    category: "others",
    isPro: false,
    views: 3100,
    likes: 1400,
    description: "Sự kiện Khai trương cửa hàng, ưu đãi khai trương hấp dẫn.",
    tags: ["event", "khai-truong", "others"],
  },
  {
    id: "t7",
    name: "LDP112311 - Dịch vụ Tư vấn tài chính",
    image: "/images/template_electronics.png",
    category: "service",
    isPro: true,
    views: 5120,
    likes: 2560,
    description: "Dịch vụ Tư vấn tài chính cá nhân và doanh nghiệp chuyên nghiệp.",
    tags: ["finance", "tai-chinh", "service"],
  },
  {
    id: "t8",
    name: "LDP112312 - Khóa học thiết kế LadiPage",
    image: "/images/template_wedding.png",
    category: "others",
    isPro: false,
    views: 2900,
    likes: 1100,
    description: "Khóa học thiết kế LadiPage chuyên sâu từ cơ bản đến nâng cao.",
    tags: ["course", "design", "others"],
  },
  {
    id: "t9",
    name: "LDP112313 - Hero Slide Show Carousel",
    image: "/images/carousel/carousel-01.png",
    category: "others",
    isPro: false,
    views: 7240,
    likes: 3610,
    description: "Hero Slide Show Carousel trình chiếu ảnh ấn tượng.",
    tags: ["carousel", "slider", "others"],
  },
  {
    id: "t10",
    name: "LDP112314 - Product Grid Flash Sale",
    image: "/images/product/smartwatch_product.png",
    category: "ecommerce",
    isPro: false,
    views: 8350,
    likes: 4180,
    description: "Product Grid Flash Sale hiển thị danh sách sản phẩm giảm giá.",
    tags: ["flash-sale", "product-grid", "ecommerce"],
  },
  {
    id: "t11",
    name: "LDP112315 - Course Funnel E-Learning",
    image: "/images/carousel/carousel-02.png",
    category: "service",
    isPro: true,
    views: 6920,
    likes: 3420,
    description: "Phễu khóa học E-Learning thu thập lead đăng ký học thử.",
    tags: ["course", "elearning", "service"],
  },
  {
    id: "t12",
    name: "LDP112316 - Gallery Showcase Portfolio",
    image: "/images/grid-image/image-01.png",
    category: "others",
    isPro: false,
    views: 5480,
    likes: 2280,
    description: "Trưng bày dự án cá nhân, portfolio đẹp mắt và hiện đại.",
    tags: ["portfolio", "gallery", "others"],
  },
  {
    id: "t13",
    name: "LDP112317 - Builder Product Kit",
    image: "/images/product/skincare_product.png",
    category: "ecommerce",
    isPro: true,
    views: 9210,
    likes: 4690,
    description: "Bộ Kit sản phẩm dành cho bán hàng trực tuyến.",
    tags: ["kit", "product", "ecommerce"],
  },
  {
    id: "t14",
    name: "LDP112318 - Builder UI Elements",
    image: "/images/grid-image/image-03.png",
    category: "service",
    isPro: false,
    views: 6370,
    likes: 3010,
    description: "Các phần tử giao diện mẫu có sẵn trong editor.",
    tags: ["ui-elements", "components", "service"],
  },
  {
    id: "t15",
    name: "SaaS Minimal Clean — Flux AI CRM",
    image: "/images/product/smartwatch_product.png",
    category: "service",
    isPro: false,
    views: 8120,
    likes: 4060,
    description: "Giao diện SaaS tối giản cho phần mềm CRM tích hợp AI.",
    tags: ["saas", "crm", "service"],
  },
  {
    id: "t16",
    name: "E-commerce Bold Offer — Flash Sale 70%",
    image: "/images/product/skincare_product.png",
    category: "ecommerce",
    isPro: false,
    views: 11430,
    likes: 5780,
    description: "Mẫu bán hàng giảm giá sốc Flash Sale lên tới 70%.",
    tags: ["flash-sale", "bold", "ecommerce"],
  },
  {
    id: "t17",
    name: "Premium Real Estate — Luxury Biệt thự",
    image: "/images/grid-image/image-01.png",
    category: "service",
    isPro: true,
    views: 5340,
    likes: 2890,
    description: "Trang giới thiệu dự án bất động sản biệt thự hạng sang.",
    tags: ["real-estate", "luxury", "service"],
  },
  {
    id: "t18",
    name: "Online Course Conversion — GrowthAcademy",
    image: "/images/carousel/carousel-02.png",
    category: "service",
    isPro: false,
    views: 9870,
    likes: 4920,
    description: "Mẫu khóa học trực tuyến GrowthAcademy tăng tỷ lệ đăng ký học.",
    tags: ["course", "growth-academy", "service"],
  },
  {
    id: "t19",
    name: "Webinar Event Modern — Growth Summit 2026",
    image: "/images/carousel/carousel-01.png",
    category: "others",
    isPro: false,
    views: 7650,
    likes: 3820,
    description: "Sự kiện hội thảo trực tuyến Webinar Growth Summit 2026.",
    tags: ["webinar", "event", "others"],
  },
  {
    id: "t20",
    name: "Agency Portfolio — VOID Studio Creative",
    image: "/images/grid-image/image-02.png",
    category: "others",
    isPro: true,
    views: 6210,
    likes: 3140,
    description: "Portfolio thiết kế sáng tạo của VOID Studio Creative.",
    tags: ["agency", "portfolio", "others"],
  },
  {
    id: "t21",
    name: "Clinic Trust Landing — VitaCare Phòng khám",
    image: "/images/grid-image/image-04.png",
    category: "service",
    isPro: false,
    views: 4980,
    likes: 2490,
    description: "Trang thông tin phòng khám VitaCare uy tín và chất lượng.",
    tags: ["clinic", "healthcare", "service"],
  },
  {
    id: "t22",
    name: "Restaurant Premium Menu — Nhà hàng Umami",
    image: "/images/grid-image/image-05.png",
    category: "service",
    isPro: false,
    views: 5720,
    likes: 2960,
    description: "Thực đơn cao cấp giới thiệu món ăn tại nhà hàng Umami.",
    tags: ["restaurant", "menu", "service"],
  },
  {
    id: "t23",
    name: "Mobile App Launch — Pendo Finance App",
    image: "/images/product/green_tea_product.png",
    category: "others",
    isPro: false,
    views: 8880,
    likes: 4440,
    description: "Giới thiệu ra mắt ứng dụng tài chính Pendo Finance App trên di động.",
    tags: ["app", "finance", "others"],
  },
  {
    id: "t24",
    name: "Finance Lead Generation — ProsperWealth",
    image: "/images/product/smartwatch_product.png",
    category: "service",
    isPro: true,
    views: 6560,
    likes: 3280,
    description: "Kênh thu thập thông tin khách hàng tiềm năng ProsperWealth.",
    tags: ["finance", "leads", "service"],
  },
  {
    id: "t25",
    name: "Beauty Spa Elegant — Lumière Spa & Skincare",
    image: "/images/product/skincare_product.png",
    category: "service",
    isPro: false,
    views: 7340,
    likes: 3670,
    description: "Giới thiệu dịch vụ spa và chăm sóc sắc đẹp Lumière.",
    tags: ["spa", "skincare", "service"],
  },
  {
    id: "t26",
    name: "Local Service Lead Gen — AirFix Điều hòa",
    image: "/images/grid-image/image-06.png",
    category: "service",
    isPro: false,
    views: 9120,
    likes: 4560,
    description: "Dịch vụ sửa chữa lắp đặt điều hòa tại nhà AirFix.",
    tags: ["service", "airfix", "repair"],
  },
];

export const templateSeedData: SeedTemplateItem[] = rawMetadata.map((meta) => {
  const presetKey = resolveTemplatePresetId({ name: meta.name, id: meta.id });
  
  // Khởi tạo blocks và chạy migration sang schema v2
  const flatBlocks = instantiateTemplateBlocks(presetKey).map(ensureOnlookBlockMeta);
  const sections = migrateTemplateFlatBlocks(flatBlocks);
  const finalSections = recalculateSectionHeights(sections);

  const editor_data = {
    pageId: "",
    pageName: meta.name,
    sections: finalSections,
    pageSettings: createDefaultPageSettings(meta.name),
    schemaVersion: CURRENT_EDITOR_SCHEMA_VERSION,
    templateId: presetKey,
  };

  return {
    template_key: presetKey,
    name: meta.name,
    description: meta.description,
    category: meta.category,
    tags: meta.tags,
    thumbnail_url: meta.image,
    preview_image_url: meta.image,
    editor_data,
    is_published: true,
    is_featured: meta.id === "t1" || meta.id === "t4" || meta.id === "t7" || meta.id === "t15",
    price_type: meta.isPro ? "pro" : "free",
    views_count: meta.views,
    downloads_count: meta.likes,
  };
});
