"use client";

import React, { useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, CheckCircle2, Circle, Clock, Loader2, AlertCircle, Sparkles } from "lucide-react";
import SeoAutomationShell from "@/features/ai-seo/components/SeoAutomationShell";

interface TaskItem {
  id: string;
  projectId: string;
  title: string;
  description?: string;
  importance: "high" | "medium" | "low";
  status: "todo" | "in_progress" | "completed";
}

export default function ProjectTasksPage() {
  const params = useParams();
  const queryClient = useQueryClient();
  const projectId = (params?.projectId as string) || "";
  const [importanceTab, setImportanceTab] = useState<"all" | "high" | "medium" | "low">("all");

  // Query Project details
  const { data: projects = [] } = useQuery<any[]>({
    queryKey: ["ai-seo-projects", { orgId: "org-1" }],
    queryFn: async () => {
      const res = await fetch("/api/ai-seo/projects");
      return res.json();
    },
  });

  const activeProject = projects.find(
    (p) => p.id === projectId || p.projectId === projectId
  );

  // Query Tasks list
  const { data: tasks = [], isLoading } = useQuery<TaskItem[]>({
    queryKey: ["seo-tasks", projectId],
    queryFn: async () => {
      const res = await fetch(`/api/ai-seo/seo-tasks?projectId=${projectId}`);
      if (!res.ok) throw new Error("Failed to fetch tasks");
      return res.json();
    },
    enabled: !!projectId,
  });

  // Toggle Task Status Mutation
  const toggleTaskMutation = useMutation({
    mutationFn: async ({
      taskId,
      nextStatus,
    }: {
      taskId: string;
      nextStatus: "todo" | "in_progress" | "completed";
    }) => {
      // Optimistic simulated update / backend call
      const res = await fetch(`/api/ai-seo/seo-tasks/${taskId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status: nextStatus }),
      });
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["seo-tasks", projectId] });
    },
  });

  const handleToggleStatus = (task: TaskItem) => {
    const statusCycle: Record<string, "todo" | "in_progress" | "completed"> = {
      todo: "in_progress",
      in_progress: "completed",
      completed: "todo",
    };
    const nextStatus = statusCycle[task.status];
    toggleTaskMutation.mutate({ taskId: task.id, nextStatus });
  };

  const filteredTasks = tasks.filter(
    (t) => importanceTab === "all" || t.importance === importanceTab
  );

  const getImportanceColor = (imp: string) => {
    if (imp === "high") return "bg-rose-50 text-rose-600 border-rose-100";
    if (imp === "medium") return "bg-amber-50 text-amber-600 border-amber-100";
    return "bg-slate-50 text-slate-500 border-slate-200";
  };

  const getStatusIcon = (status: string) => {
    if (status === "completed") {
      return <CheckCircle2 className="w-5 h-5 text-emerald-550 shrink-0" />;
    }
    if (status === "in_progress") {
      return <Clock className="w-5 h-5 text-violet-500 shrink-0" />;
    }
    return <Circle className="w-5 h-5 text-slate-300 shrink-0 hover:text-slate-450 transition" />;
  };

  return (
    <SeoAutomationShell>
      <div className="max-w-5xl w-full mx-auto p-6 md:p-8 space-y-6 text-left">
        {/* Back Link */}
        <Link
          href="/ai-seo"
          className="inline-flex items-center gap-1.5 text-xs font-bold text-slate-400 hover:text-white transition"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Dashboard
        </Link>

        {/* Title */}
        <div className="flex flex-col md:flex-row md:items-center justify-between border-b border-slate-805 pb-5 gap-4">
          <div className="space-y-1">
            <h1 className="text-2xl font-black text-white tracking-tight flex items-center gap-2">
              <Sparkles className="w-6 h-6 text-violet-400" />
              SEO Optimizations
            </h1>
            <p className="text-xs text-slate-400 font-semibold leading-relaxed">
              Active optimization tasks and recommendations generated by OTTO SEO for{" "}
              <span className="text-slate-250 underline">
                {activeProject?.hostname || "your website"}
              </span>
            </p>
          </div>

          {/* Importance tabs */}
          <div className="flex items-center gap-1 bg-slate-900 p-1 rounded-xl shrink-0">
            {(["all", "high", "medium", "low"] as const).map((tab) => (
              <button
                key={tab}
                onClick={() => setImportanceTab(tab)}
                className={`px-3 py-1.5 rounded-lg text-[10px] font-extrabold uppercase tracking-wide transition duration-150 ${
                  importanceTab === tab
                    ? "bg-slate-800 text-white"
                    : "text-slate-500 hover:text-slate-350"
                }`}
              >
                {tab}
              </button>
            ))}
          </div>
        </div>

        {/* Tasks List */}
        {isLoading ? (
          <div className="flex flex-col items-center justify-center py-20 text-slate-400">
            <Loader2 className="w-8 h-8 animate-spin text-violet-500 mb-2" />
            <span className="text-xs font-bold">Đang tải danh sách đề xuất...</span>
          </div>
        ) : filteredTasks.length === 0 ? (
          <div className="text-center py-16 border border-dashed border-slate-800 rounded-2xl p-8 max-w-sm mx-auto space-y-3">
            <AlertCircle className="w-10 h-10 text-slate-600 mx-auto" />
            <h4 className="text-xs font-bold text-white uppercase tracking-wider">
              No tasks found
            </h4>
            <p className="text-[11px] text-slate-500 font-semibold leading-normal">
              OTTO SEO has verified all criteria. Run another manual scan to audit pages for updates.
            </p>
          </div>
        ) : (
          <div className="space-y-3">
            {filteredTasks.map((task) => (
              <div
                key={task.id}
                onClick={() => handleToggleStatus(task)}
                className={`flex items-start gap-4 p-4 border rounded-2xl bg-slate-900/60 border-slate-800 hover:border-slate-700 transition cursor-pointer select-none ${
                  task.status === "completed" ? "opacity-60" : ""
                }`}
              >
                {/* Checkbox Trigger */}
                <div className="mt-0.5">{getStatusIcon(task.status)}</div>

                {/* Content */}
                <div className="flex-1 space-y-1.5 min-w-0 text-left">
                  <div className="flex items-center gap-2 flex-wrap">
                    <h3
                      className={`text-xs font-bold text-white tracking-wide ${
                        task.status === "completed" ? "line-through text-slate-500" : ""
                      }`}
                    >
                      {task.title}
                    </h3>
                    <span
                      className={`px-1.5 py-0.5 rounded text-[8px] font-black uppercase border tracking-wider ${getImportanceColor(
                        task.importance
                      )}`}
                    >
                      {task.importance}
                    </span>
                  </div>
                  {task.description && (
                    <p className="text-[11px] text-slate-400 font-medium leading-relaxed">
                      {task.description}
                    </p>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </SeoAutomationShell>
  );
}
