import { LandingTemplatePreset } from "./shared";

export const THEMED_TEMPLATE_PRESETS: LandingTemplatePreset[] = [
  // ─── 12 NEW TEMPLATES ─────────────────────────────────────────────────────

  // Template 1 — SaaS Minimal Clean
  {
    id: "saas-minimal",
    name: "SaaS Minimal Clean",
    description: "B2B SaaS, CRM, automation — minimal whitespace, indigo accent, high trust.",
    category: "section",
    blocks: [
      {
        type: "menu",
        label: "SaaS Nav",
        props: {
          logoText: "Flux AI",
          logoUrl: "#",
          items: [
            { label: "Features", url: "#features" },
            { label: "Pricing", url: "#pricing" },
            { label: "FAQ", url: "#faq" },
            { label: "Get Started", url: "#cta" },
          ],
          bgColor: "#ffffff",
          textColor: "#1e293b",
        },
      },
      {
        type: "hero",
        label: "Hero SaaS",
        props: {
          headline: "Automate your entire sales pipeline with AI",
          subheadline: "Flux connects your CRM, email, and data sources in one intelligent workspace. No code required.",
          ctaText: "Start free — no credit card",
          ctaUrl: "#cta",
          ctaColor: "#6366f1",
          bgColor: "#f8f7ff",
          bgImage: "/images/banners/saas-minimal.png",
          textAlign: "center",
          minHeight: 720,
          overlayOpacity: 0.5,
        },
      },
      {
        type: "collection_list",
        label: "Social proof logos",
        props: {
          items: [
            { id: "c1", title: "Shopify", desc: "Trusted by 10,000+ teams", icon: "01" },
            { id: "c2", title: "Notion", desc: "98% retention rate", icon: "02" },
            { id: "c3", title: "Stripe", desc: "4.9★ on G2", icon: "03" },
          ],
          columns: 3,
          layout: "grid",
          bgColor: "#f1f5f9",
        },
      },
      {
        type: "feature_card",
        label: "Feature — AI Inbox",
        props: {
          icon: "✦",
          iconColor: "#6366f1",
          iconBg: "#eef2ff",
          title: "AI-powered inbox",
          description: "Let the AI prioritize, label and draft replies for every incoming lead — 10× faster than manual triage.",
          bgColor: "#ffffff",
          borderColor: "#e0e7ff",
          borderRadius: 20,
        },
      },
      {
        type: "feature_card",
        label: "Feature — Workflow",
        props: {
          icon: "◈",
          iconColor: "#0ea5e9",
          iconBg: "#e0f2fe",
          title: "Visual workflow builder",
          description: "Drag-and-drop automation sequences. Connect triggers, conditions and actions without writing code.",
          bgColor: "#ffffff",
          borderColor: "#bae6fd",
          borderRadius: 20,
        },
      },
      {
        type: "feature_card",
        label: "Feature — Analytics",
        props: {
          icon: "▣",
          iconColor: "#10b981",
          iconBg: "#d1fae5",
          title: "Revenue analytics",
          description: "Real-time dashboards for MRR, churn, pipeline velocity and team performance.",
          bgColor: "#ffffff",
          borderColor: "#a7f3d0",
          borderRadius: 20,
        },
      },
      {
        type: "tabs",
        label: "3-step workflow",
        props: {
          tabs: [
            { id: "step1", label: "1. Connect", content: "Link your CRM, email and calendar in under 5 minutes via OAuth integrations." },
            { id: "step2", label: "2. Automate", content: "Set up trigger-based sequences. The AI learns your top reps' patterns and replicates them." },
            { id: "step3", label: "3. Close", content: "Focus only on hot leads. Let Flux handle follow-ups, reminders and pipeline hygiene." },
          ],
          activeTabId: "step1",
          style: "underline",
          accentColor: "#6366f1",
        },
      },
      {
        type: "table",
        label: "Pricing comparison",
        props: {
          headers: ["Plan", "Seats", "Automations", "Price"],
          rows: [
            ["Starter", "1 user", "50/month", "Free"],
            ["Growth", "5 users", "Unlimited", "$49/mo"],
            ["Scale", "Unlimited", "Unlimited + AI", "$149/mo"],
          ],
          bgColor: "#ffffff",
          borderColor: "#e2e8f0",
        },
      },
      {
        type: "accordion",
        label: "FAQ SaaS",
        props: {
          items: [
            { id: "q1", question: "Is there a free trial?", answer: "Yes — our Starter plan is free forever. Upgrade anytime as your team grows." },
            { id: "q2", question: "Can I import existing CRM data?", answer: "Flux supports CSV import and direct integrations with Salesforce, HubSpot, Pipedrive." },
            { id: "q3", question: "How does AI respond on behalf of me?", answer: "AI drafts responses in your tone. You review before send — always in control." },
          ],
          allowMultiple: false,
          accentColor: "#6366f1",
        },
      },
      {
        type: "collection_list",
        label: "SaaS social stats",
        props: {
          items: [
            { id: "s1", title: "12,000+", desc: "Teams active worldwide", icon: "01" },
            { id: "s2", title: "98%", desc: "Customer retention rate", icon: "02" },
            { id: "s3", title: "4.9 / 5", desc: "Average rating on G2 & Capterra", icon: "03" },
            { id: "s4", title: "$2.4B", desc: "Revenue processed by clients", icon: "04" },
          ],
          columns: 4,
          layout: "grid",
          bgColor: "#eef2ff",
        },
      },
      {
        type: "testimonial",
        label: "SaaS testimonial 2",
        props: {
          quote: "Flux replaced 4 separate tools we were paying for. Pipeline went from 45 days to 19 days average close time. ROI was visible in week 1.",
          authorName: "Marcus Lee",
          authorRole: "VP Sales @ Orbit Commerce — 120-person team",
          authorAvatar: "",
          rating: 5,
          bgColor: "#f8f7ff",
          textColor: "#1e293b",
          showRating: true,
        },
      },
      {
        type: "form_capture",
        label: "Final CTA SaaS",
        props: {
          title: "Start your free workspace",
          subtitle: "Join 12,000+ teams. Set up in 5 minutes.",
          fields: [
            { id: "email", label: "Work email", type: "email", required: true },
            { id: "name", label: "Full name", type: "text", required: true },
          ],
          submitLabel: "Create free account",
          submitColor: "#6366f1",
          bgColor: "#f8f7ff",
          borderRadius: 16,
        },
      },
    ],
  },

  // Template 2 — E-commerce Bold Offer
  {
    id: "ecommerce-bold",
    name: "E-commerce Bold Offer",
    description: "Flash sale, D2C brand — aggressive CTA, countdown urgency, dark red tone.",
    category: "page",
    blocks: [
      {
        type: "hero",
        label: "Hero Bold Offer",
        props: {
          headline: "🔥 FLASH SALE — UP TO 70% OFF TODAY ONLY",
          subheadline: "Hàng giới hạn. Ưu đãi kết thúc lúc nửa đêm. Đặt ngay để giữ giá tốt nhất.",
          ctaText: "MUA NGAY — GIÁ TỐT NHẤT",
          ctaUrl: "#order",
          ctaColor: "#fbbf24",
          bgColor: "#0f0000",
          bgImage: "/images/banners/ecommerce-bold.png",
          textAlign: "center",
          minHeight: 680,
          overlayOpacity: 0.6,
        },
      },
      {
        type: "countdown",
        label: "Urgency countdown",
        props: {
          targetDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
          title: "⚡ Ưu đãi kết thúc sau",
          expiredText: "Ưu đãi đã hết hạn",
          bgColor: "#7f1d1d",
          accentColor: "#fbbf24",
        },
      },
      {
        type: "product_card",
        label: "Flash sale products",
        props: {
          title: "DEAL HOT",
          description: "Chọn sản phẩm ưa thích",
          price: "390.000đ",
          oldPrice: "990.000đ",
          image: "/images/product/skincare_product.png",
          badge: "-60%",
          ctaText: "THÊM VÀO GIỎ",
          bgColor: "#1c0202",
          borderColor: "#7f1d1d",
          borderRadius: 12,
          columns: 3,
          items: [
            { id: "p1", title: "Serum Pro X5", description: "Căng bóng da tức thì.", price: "390.000đ", oldPrice: "990.000đ", image: "/images/product/skincare_product.png", badge: "-60%" },
            { id: "p2", title: "Smartwatch Titan", description: "Pin 24h, GPS, chống nước.", price: "890.000đ", oldPrice: "2.490.000đ", image: "/images/product/smartwatch_product.png", badge: "-64%" },
            { id: "p3", title: "Organic Tea Set", description: "Combo 3 vị thảo mộc.", price: "190.000đ", oldPrice: "450.000đ", image: "/images/product/green_tea_product.png", badge: "-58%" },
          ],
        },
      },
      {
        type: "collection_list",
        label: "Purchase benefits",
        props: {
          items: [
            { id: "b1", title: "Giao nhanh 2h", desc: "Nội thành HN & HCM. Toàn quốc 1-2 ngày.", icon: "01" },
            { id: "b2", title: "Hoàn tiền 100%", desc: "Nếu không hài lòng trong 7 ngày.", icon: "02" },
            { id: "b3", title: "COD toàn quốc", desc: "Thanh toán khi nhận hàng.", icon: "03" },
          ],
          columns: 3,
          layout: "grid",
          bgColor: "#7f1d1d",
        },
      },
      {
        type: "testimonial",
        label: "Bold review",
        props: {
          quote: "Mua lần đầu đã ghiền. Giao hàng nhanh, đóng gói đẹp, sản phẩm chuẩn y mô tả. Chắc chắn mua lại!",
          authorName: "Nguyễn Hương Ly",
          authorRole: "Khách hàng đã xác minh ⭐⭐⭐⭐⭐",
          authorAvatar: "",
          rating: 5,
          bgColor: "#1c0202",
          textColor: "#fde8e8",
          showRating: true,
        },
      },
      {
        type: "collection_list",
        label: "Flash sale stats",
        props: {
          items: [
            { id: "s1", title: "50,000+", desc: "Đơn hàng đã giao thành công", icon: "01" },
            { id: "s2", title: "4.9 ★", desc: "Đánh giá trên Shopee & TikTok Shop", icon: "02" },
            { id: "s3", title: "< 2 giờ", desc: "Thời gian giao hàng nội thành", icon: "03" },
            { id: "s4", title: "100%", desc: "Hoàn tiền nếu không hài lòng", icon: "04" },
          ],
          columns: 4,
          layout: "grid",
          bgColor: "#7f1d1d",
        },
      },
      {
        type: "collection_list",
        label: "Shipping & policy",
        props: {
          items: [
            { id: "p1", title: "🚀 Giao siêu tốc", desc: "2 giờ nội thành HN & HCM. Toàn quốc 1–2 ngày làm việc qua GHTK, GHN.", icon: "01" },
            { id: "p2", title: "🔒 Thanh toán an toàn", desc: "COD, VNPAY, MoMo, ZaloPay, thẻ tín dụng Visa/Mastercard.", icon: "02" },
            { id: "p3", title: "🔄 Đổi trả 7 ngày", desc: "Hoàn tiền 100% nếu sản phẩm lỗi hoặc không đúng mô tả.", icon: "03" },
          ],
          columns: 3,
          layout: "grid",
          bgColor: "#0f0000",
        },
      },
      {
        type: "form_capture",
        label: "Quick checkout form",
        props: {
          title: "Đặt hàng ngay — Giao trong 2h",
          subtitle: "Điền thông tin, đội ngũ sẽ gọi xác nhận đơn trong 5 phút.",
          fields: [
            { id: "name", label: "Họ và tên", type: "text", required: true },
            { id: "phone", label: "Số điện thoại", type: "phone", required: true },
            { id: "address", label: "Địa chỉ giao hàng", type: "text", required: true },
          ],
          submitLabel: "ĐẶT HÀNG NGAY 🔥",
          submitColor: "#dc2626",
          bgColor: "#0f0000",
          borderRadius: 12,
        },
      },
    ],
  },

  // Template 3 — Premium Real Estate
  {
    id: "real-estate-premium",
    name: "Premium Real Estate",
    description: "Luxury villa, resort, apartment — black gold, full-screen hero, booking form.",
    category: "page",
    blocks: [
      {
        type: "menu",
        label: "Real Estate Nav",
        props: {
          logoText: "AURA RESIDENCES",
          logoUrl: "#",
          items: [
            { label: "Overview", url: "#overview" },
            { label: "Gallery", url: "#gallery" },
            { label: "Pricing", url: "#pricing" },
            { label: "Book Viewing", url: "#book" },
          ],
          bgColor: "#0a0a0a",
          textColor: "#d4af6a",
        },
      },
      {
        type: "hero",
        label: "Hero Real Estate",
        props: {
          headline: "WHERE LUXURY MEETS NATURE",
          subheadline: "Aura Residences — Biệt thự cao cấp ven hồ, hướng núi, thiết kế bởi kiến trúc sư quốc tế.",
          ctaText: "Đặt lịch tham quan",
          ctaUrl: "#book",
          ctaColor: "#d4af6a",
          bgColor: "#0a0a0a",
          bgImage: "/images/grid-image/image-01.png",
          textAlign: "center",
          minHeight: 620,
          overlayOpacity: 0.5,
        },
      },
      {
        type: "table",
        label: "Project specs",
        props: {
          headers: ["Thông số", "Chi tiết"],
          rows: [
            ["Vị trí", "Hồ Tây, Hà Nội — mặt tiền hồ"],
            ["Diện tích", "Từ 280m² – 450m²"],
            ["Giá từ", "18 tỷ VNĐ"],
            ["Pháp lý", "Sổ đỏ lâu dài, sang tên 30 ngày"],
            ["Bàn giao", "Hoàn thiện cao cấp, Q4/2026"],
          ],
          bgColor: "#111111",
          borderColor: "#2a2a2a",
        },
      },
      {
        type: "gallery",
        label: "Project gallery",
        props: {
          images: [
            "/images/grid-image/image-01.png",
            "/images/grid-image/image-02.png",
            "/images/grid-image/image-03.png",
            "/images/grid-image/image-04.png",
            "/images/grid-image/image-05.png",
            "/images/grid-image/image-06.png",
          ],
          columns: 3,
          gap: 8,
          borderRadius: 8,
          aspectRatio: "4/3",
        },
      },
      {
        type: "collection_list",
        label: "Investment reasons",
        props: {
          items: [
            { id: "r1", title: "Vị trí độc tôn", desc: "Chỉ 28 căn, không có thêm căn nào sẽ được phép xây dựng trong bán kính 500m.", icon: "01" },
            { id: "r2", title: "Giá trị tăng trưởng", desc: "BĐS ven hồ Hà Nội tăng trung bình 18%/năm trong 5 năm qua.", icon: "02" },
            { id: "r3", title: "Bảo lãnh pháp lý", desc: "Công chứng sổ đỏ trong 30 ngày, không rủi ro pháp lý.", icon: "03" },
          ],
          columns: 3,
          layout: "grid",
          bgColor: "#1a1500",
        },
      },
      {
        type: "accordion",
        label: "Real estate FAQ",
        props: {
          items: [
            { id: "q1", question: "Chính sách thanh toán như thế nào?", answer: "Thanh toán 30% khi ký hợp đồng, 40% khi bàn giao, 30% sau 12 tháng. Hỗ trợ vay ngân hàng lên đến 70%." },
            { id: "q2", question: "Có thể cho thuê lại không?", answer: "Có. Dự án có đội quản lý vận hành, hỗ trợ cho thuê ngắn hạn qua Airbnb hoặc dài hạn." },
          ],
          allowMultiple: false,
          accentColor: "#d4af6a",
        },
      },
      {
        type: "collection_list",
        label: "Real estate stats",
        props: {
          items: [
            { id: "r1", title: "28 căn", desc: "Số lượng giới hạn, không mở bán thêm", icon: "01" },
            { id: "r2", title: "280–450m²", desc: "Diện tích sàn mỗi căn biệt thự", icon: "02" },
            { id: "r3", title: "18 tỷ+", desc: "Giá khởi điểm theo vị trí", icon: "03" },
            { id: "r4", title: "Q4/2026", desc: "Dự kiến bàn giao hoàn thiện", icon: "04" },
          ],
          columns: 4,
          layout: "grid",
          bgColor: "#1a1500",
        },
      },
      {
        type: "testimonial",
        label: "Investor testimonial",
        props: {
          quote: "Đây là khoản đầu tư tốt nhất tôi thực hiện trong 10 năm qua. Vị trí hồ Tây không thể thay thế — giá trị chỉ có một chiều duy nhất là đi lên.",
          authorName: "Nguyễn Thành Long",
          authorRole: "Nhà đầu tư — Đã mua 2 căn Aura Residences",
          authorAvatar: "",
          rating: 5,
          bgColor: "#111111",
          textColor: "#d4af6a",
          showRating: true,
        },
      },
      {
        type: "form_capture",
        label: "Property viewing form",
        props: {
          title: "Đăng ký nhận bảng giá & đặt lịch tham quan",
          subtitle: "Chuyên viên sẽ liên hệ trong vòng 30 phút trong giờ hành chính.",
          fields: [
            { id: "name", label: "Họ và tên", type: "text", required: true },
            { id: "phone", label: "Số điện thoại", type: "phone", required: true },
            { id: "budget", label: "Ngân sách dự kiến", type: "text", required: false },
          ],
          submitLabel: "Nhận bảng giá ngay",
          submitColor: "#d4af6a",
          bgColor: "#0a0a0a",
          borderRadius: 12,
        },
      },
    ],
  },

  // Template 4 — Online Course Conversion
  {
    id: "online-course",
    name: "Online Course Conversion",
    description: "Bootcamp, marketing, lập trình — navy + cam, curriculum tabs, lead form.",
    category: "page",
    blocks: [
      {
        type: "menu",
        label: "Course Nav",
        props: {
          logoText: "GrowthAcademy",
          logoUrl: "#",
          items: [
            { label: "Giáo trình", url: "#curriculum" },
            { label: "Giảng viên", url: "#instructor" },
            { label: "Học phí", url: "#pricing" },
            { label: "Đăng ký", url: "#enroll" },
          ],
          bgColor: "#1e3a5f",
          textColor: "#ffffff",
        },
      },
      {
        type: "hero",
        label: "Hero Course",
        props: {
          headline: "Thành thạo Digital Marketing trong 8 tuần",
          subheadline: "Từ zero → chạy được Facebook Ads, SEO, Email Automation. Học thực chiến, có portfolio thật.",
          ctaText: "Đăng ký học thử miễn phí",
          ctaUrl: "#enroll",
          ctaColor: "#f97316",
          bgColor: "#1e3a5f",
          bgImage: "/images/banners/online-course.png",
          textAlign: "left",
          minHeight: 520,
          overlayOpacity: 0.65,
        },
      },
      {
        type: "collection_list",
        label: "Pain points",
        props: {
          items: [
            { id: "p1", title: "Tốn tiền ads mà không có đơn?", desc: "Thiếu hệ thống bài bản, ngân sách cạn trước khi thấy kết quả.", icon: "01" },
            { id: "p2", title: "Không biết tracking & đo lường?", desc: "Chạy chiến dịch mà không biết kênh nào hiệu quả.", icon: "02" },
            { id: "p3", title: "Content làm rồi không ai xem?", desc: "Thiếu chiến lược phân phối và SEO cơ bản.", icon: "03" },
          ],
          columns: 3,
          layout: "grid",
          bgColor: "#0c2340",
        },
      },
      {
        type: "tabs",
        label: "Curriculum modules",
        props: {
          tabs: [
            { id: "m1", label: "Module 1", content: "Nền tảng Marketing số: Customer journey, funnel, KPIs cần theo dõi. Thực hành: Phân tích 3 case study thật." },
            { id: "m2", label: "Module 2", content: "Facebook & TikTok Ads: Cài Pixel, tạo Custom Audience, A/B test creative. Thực hành: Chạy chiến dịch thật với ngân sách $20." },
            { id: "m3", label: "Module 3", content: "SEO & Content Strategy: Keyword research, on-page, link building. Thực hành: Viết 5 bài chuẩn SEO lên top Google." },
            { id: "m4", label: "Module 4", content: "Email & Automation: Xây dựng email sequence, A/B test, CRM sync. Thực hành: Dựng toàn bộ automation cho 1 sản phẩm." },
          ],
          activeTabId: "m1",
          style: "pills",
          accentColor: "#f97316",
        },
      },
      {
        type: "feature_card",
        label: "Instructor profile",
        props: {
          icon: "★",
          iconColor: "#f97316",
          iconBg: "#fff7ed",
          title: "Trần Minh Khoa — Senior Growth Marketer",
          description: "10 năm kinh nghiệm tại Shopee, VNG, Tiki. Đã scale hơn 200 chiến dịch đạt ROAS trên 5x. Mentor tại MMA, SEA.",
          bgColor: "#f0f9ff",
          borderColor: "#bae6fd",
          borderRadius: 16,
        },
      },
      {
        type: "testimonial",
        label: "Student review",
        props: {
          quote: "Sau 8 tuần tôi tự chạy được chiến dịch đầu tiên đạt 4.2x ROAS. Khóa học này khác hoàn toàn so với những gì tôi học trên YouTube.",
          authorName: "Phạm Thu Hà",
          authorRole: "Học viên Cohort 7 — Digital Marketing Lead @ Startup",
          authorAvatar: "",
          rating: 5,
          bgColor: "#fff7ed",
          textColor: "#1e3a5f",
          showRating: true,
        },
      },
      {
        type: "table",
        label: "Course packages",
        props: {
          headers: ["Gói", "Hình thức", "Giá"],
          rows: [
            ["Online Self-paced", "Video ghi hình + bài tập", "2.900.000đ"],
            ["Live + Mentor", "Học live 2 buổi/tuần + 1:1 với mentor", "5.900.000đ"],
            ["VIP Bootcamp", "Học live + project thật + job referral", "9.900.000đ"],
          ],
          bgColor: "#ffffff",
          borderColor: "#e2e8f0",
        },
      },
      {
        type: "accordion",
        label: "Course FAQ",
        props: {
          items: [
            { id: "q1", question: "Học online có khó không nếu tôi chưa biết gì?", answer: "Không. Module 1 bắt đầu từ cơ bản. Chỉ cần có laptop và internet là đủ." },
            { id: "q2", question: "Có được hỗ trợ sau khi học xong không?", answer: "Gói Mentor và VIP có nhóm Slack riêng, hỗ trợ 6 tháng sau khi hoàn thành." },
          ],
          allowMultiple: true,
          accentColor: "#f97316",
        },
      },
      {
        type: "collection_list",
        label: "Course outcome stats",
        props: {
          items: [
            { id: "o1", title: "2,400+", desc: "Học viên đã tốt nghiệp", icon: "01" },
            { id: "o2", title: "87%", desc: "Tìm được việc / tăng thu nhập sau 3 tháng", icon: "02" },
            { id: "o3", title: "4.8 / 5", desc: "Điểm hài lòng trung bình của học viên", icon: "03" },
            { id: "o4", title: "8 tuần", desc: "Thời gian học từ zero đến có portfolio", icon: "04" },
          ],
          columns: 4,
          layout: "grid",
          bgColor: "#0c2340",
        },
      },
      {
        type: "feature_card",
        label: "Community benefit",
        props: {
          icon: "🌐",
          iconColor: "#f97316",
          iconBg: "#fff7ed",
          title: "Cộng đồng 2,400+ alumni",
          description: "Sau khi tốt nghiệp, bạn gia nhập nhóm alumni riêng — nơi chia sẻ job, freelance, hỏi đáp chuyên sâu và kết nối các marketer thực chiến trên khắp cả nước.",
          bgColor: "#fff7ed",
          borderColor: "#fed7aa",
          borderRadius: 16,
        },
      },
      {
        type: "form_capture",
        label: "Enroll form",
        props: {
          title: "Đăng ký học thử 1 buổi miễn phí",
          subtitle: "Tham gia buổi học thử để quyết định. Không áp lực, không phí.",
          fields: [
            { id: "name", label: "Họ và tên", type: "text", required: true },
            { id: "phone", label: "Số điện thoại", type: "phone", required: true },
            { id: "goal", label: "Mục tiêu học", type: "text", required: false },
          ],
          submitLabel: "Đăng ký học thử ngay",
          submitColor: "#f97316",
          bgColor: "#f0f9ff",
          borderRadius: 16,
        },
      },
    ],
  },

  // Template 5 — Webinar Event Modern
  {
    id: "webinar-event",
    name: "Webinar Event Modern",
    description: "Live event, workshop, online conference — purple/neon, countdown, speaker cards.",
    category: "page",
    blocks: [
      {
        type: "hero",
        label: "Hero Event",
        props: {
          headline: "GROWTH SUMMIT 2026 — Live Online Conference",
          subheadline: "3 ngày, 18 diễn giả, 2.000+ marketer. Chủ đề: Scale your business with AI & Automation.",
          ctaText: "Đăng ký tham dự — FREE",
          ctaUrl: "#register",
          ctaColor: "#a855f7",
          bgColor: "#1a0d2e",
          bgImage: "/images/banners/webinar-event.png",
          textAlign: "center",
          minHeight: 740,
          overlayOpacity: 0.6,
        },
      },
      {
        type: "countdown",
        label: "Event countdown",
        props: {
          targetDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
          title: "Sự kiện bắt đầu sau",
          expiredText: "Sự kiện đang diễn ra — Tham gia ngay!",
          bgColor: "#2d1b4e",
          accentColor: "#a855f7",
        },
      },
      {
        type: "collection_list",
        label: "Speaker lineup",
        props: {
          items: [
            { id: "s1", title: "Sarah Chen", desc: "CMO @ Scale.ai — Growth & AI Marketing", icon: "01" },
            { id: "s2", title: "Minh Trần", desc: "Founder @ GrowthKit — SaaS Distribution", icon: "02" },
            { id: "s3", title: "Linh Nguyễn", desc: "Head of Growth @ Tiki — Retention loops", icon: "03" },
          ],
          columns: 3,
          layout: "grid",
          bgColor: "#2d1b4e",
        },
      },
      {
        type: "tabs",
        label: "Event agenda",
        props: {
          tabs: [
            { id: "day1", label: "Ngày 1 — AI", content: "Keynote: AI trong marketing 2026. Workshop: Xây dựng chatbot lead gen. Panel: Scale với 0 thêm nhân viên." },
            { id: "day2", label: "Ngày 2 — Paid", content: "Masterclass: TikTok Ads advanced. Workshop: Google Performance Max. Case study: 10x ROAS trong 60 ngày." },
            { id: "day3", label: "Ngày 3 — Growth", content: "Product-led growth. Email automation deep dive. Networking & Sponsor expo." },
          ],
          activeTabId: "day1",
          style: "pills",
          accentColor: "#a855f7",
        },
      },
      {
        type: "survey",
        label: "Who should attend",
        props: {
          question: "Bạn là ai? (Chọn để nhận gợi ý sessions phù hợp)",
          options: ["Marketer / Growth hacker", "Founder / CEO", "Agency / Freelancer", "Student đang học"],
          accentColor: "#a855f7",
          submitLabel: "Nhận gợi ý sessions",
        },
      },
      {
        type: "accordion",
        label: "Event FAQ",
        props: {
          items: [
            { id: "q1", question: "Sự kiện có thu phí không?", answer: "Free ticket cho early birds. VIP ticket 990k bao gồm recording và networking dinner." },
            { id: "q2", question: "Có bản ghi lại không?", answer: "Ticket VIP nhận full recording trong 30 ngày sau sự kiện." },
          ],
          allowMultiple: false,
          accentColor: "#a855f7",
        },
      },
      {
        type: "collection_list",
        label: "Webinar stats",
        props: {
          items: [
            { id: "w1", title: "12,000+", desc: "Người đăng ký qua 3 kỳ trước", icon: "01" },
            { id: "w2", title: "48 diễn giả", desc: "Thuộc Top 1% trong ngành", icon: "02" },
            { id: "w3", title: "100% live", desc: "Phên hỏi đáp trực tiếp, không record", icon: "03" },
            { id: "w4", title: "Bằng chứng nhận", desc: "Xác nhận bởi Growth Academy", icon: "04" },
          ],
          columns: 4,
          layout: "grid",
          bgColor: "#2d1457",
        },
      },
      {
        type: "testimonial",
        label: "Past attendee quote",
        props: {
          quote: "Growth Summit thay đổi cách tôi nhìn kinh doanh hoàn toàn. Tôi đã áp dụng 3 framework ngay sau kết thúc và doanh số tăng 34% trong tháng đầu tiên.",
          authorName: "Trần Minh Khôi",
          authorRole: "CMO @ NeoRetail — Tham dự Growth Summit 2025",
          authorAvatar: "",
          rating: 5,
          bgColor: "#1a0d2e",
          textColor: "#e2d9f3",
          showRating: true,
        },
      },
      {
        type: "form_capture",
        label: "Event registration",
        props: {
          title: "Đăng ký giữ chỗ miễn phí",
          subtitle: "Chỉ còn 400 vé. Link tham gia gửi qua email trước 24h.",
          fields: [
            { id: "name", label: "Họ và tên", type: "text", required: true },
            { id: "email", label: "Email", type: "email", required: true },
            { id: "company", label: "Công ty / Tổ chức", type: "text", required: false },
          ],
          submitLabel: "Giữ chỗ ngay — Miễn phí",
          submitColor: "#a855f7",
          bgColor: "#1a0d2e",
          borderRadius: 16,
        },
      },
    ],
  },

  // Template 6 — Creative Agency Portfolio
  {
    id: "agency-portfolio",
    name: "Creative Agency Portfolio",
    description: "Design/marketing agency — editorial black, teal neon, big typography, work showcase.",
    category: "section",
    blocks: [
      {
        type: "menu",
        label: "Agency Nav",
        props: {
          logoText: "VOID Studio",
          logoUrl: "#",
          items: [
            { label: "Work", url: "#work" },
            { label: "Services", url: "#services" },
            { label: "Process", url: "#process" },
            { label: "Contact", url: "#contact" },
          ],
          bgColor: "#0a0a0a",
          textColor: "#2dd4bf",
        },
      },
      {
        type: "hero",
        label: "Hero Agency",
        props: {
          headline: "We build brands that actually convert.",
          subheadline: "Strategy, design, and growth engineering for D2C brands and SaaS companies serious about revenue.",
          ctaText: "View our work ↗",
          ctaUrl: "#work",
          ctaColor: "#2dd4bf",
          bgColor: "#0a0a0a",
          bgImage: "/images/banners/agency-portfolio.png",
          textAlign: "left",
          minHeight: 780,
          overlayOpacity: 0.7,
        },
      },
      {
        type: "gallery",
        label: "Portfolio grid",
        props: {
          images: [
            "/images/grid-image/image-01.png",
            "/images/grid-image/image-02.png",
            "/images/grid-image/image-03.png",
            "/images/grid-image/image-04.png",
          ],
          columns: 2,
          gap: 6,
          borderRadius: 4,
          aspectRatio: "16/9",
        },
      },
      {
        type: "tabs",
        label: "Agency services",
        props: {
          tabs: [
            { id: "brand", label: "Branding", content: "Bộ nhận diện thương hiệu từ logo, typography, color system đến brand voice — nhất quán trên mọi kênh." },
            { id: "web", label: "Web & Landing", content: "Landing page tối ưu chuyển đổi, web app, dashboard. Thiết kế và dev bàn giao trong 2-4 tuần." },
            { id: "growth", label: "Growth Eng.", content: "Hệ thống tracking, A/B testing, CRO và automation. Chúng tôi đo được mọi thứ chúng tôi xây." },
          ],
          activeTabId: "brand",
          style: "underline",
          accentColor: "#2dd4bf",
        },
      },
      {
        type: "collection_list",
        label: "Working process",
        props: {
          items: [
            { id: "p1", title: "01 — Brief", desc: "Tìm hiểu business, ICP, goals. Output: Strategy doc + creative direction.", icon: "01" },
            { id: "p2", title: "02 — Design", desc: "Prototype trên Figma. 2 vòng feedback. Pixel-perfect handoff.", icon: "02" },
            { id: "p3", title: "03 — Launch", desc: "Dev và deploy. Tracking setup. A/B testing sau launch.", icon: "03" },
          ],
          columns: 3,
          layout: "grid",
          bgColor: "#111111",
        },
      },
      {
        type: "testimonial",
        label: "Client testimonial",
        props: {
          quote: "VOID Studio không chỉ làm đẹp — họ hiểu business. Campaign launch của chúng tôi đạt 3.8x ROAS ngay tháng đầu nhờ landing page họ thiết kế.",
          authorName: "Alex Kim",
          authorRole: "CEO @ Fenix Commerce, D2C Fashion Brand",
          authorAvatar: "",
          rating: 5,
          bgColor: "#0a0a0a",
          textColor: "#e2e8f0",
          showRating: true,
        },
      },
      {
        type: "collection_list",
        label: "Agency credentials",
        props: {
          items: [
            { id: "a1", title: "140+", desc: "Projects delivered globally", icon: "01" },
            { id: "a2", title: "8 years", desc: "Of premium design & dev", icon: "02" },
            { id: "a3", title: "24h", desc: "Average first concept turnaround", icon: "03" },
            { id: "a4", title: "Forbes", desc: "Featured in Forbes & Adweek", icon: "04" },
          ],
          columns: 4,
          layout: "grid",
          bgColor: "#111111",
        },
      },
      {
        type: "testimonial",
        label: "Client testimonial",
        props: {
          quote: "VOID Studio delivered a rebrand that tripled our inbound leads in 60 days. Their process is transparent, fast, and the output is world-class.",
          authorName: "Sophia Hartmann",
          authorRole: "CEO @ Lumen Digital — Berlin",
          authorAvatar: "",
          rating: 5,
          bgColor: "#0a0a0a",
          textColor: "#2dd4bf",
          showRating: true,
        },
      },
      {
        type: "form_capture",
        label: "Agency contact",
        props: {
          title: "Let's talk about your project",
          subtitle: "We take 3 new clients per month. Apply early.",
          fields: [
            { id: "name", label: "Your name", type: "text", required: true },
            { id: "email", label: "Work email", type: "email", required: true },
            { id: "project", label: "Project type & budget", type: "text", required: true },
          ],
          submitLabel: "Send brief →",
          submitColor: "#2dd4bf",
          bgColor: "#111111",
          borderRadius: 8,
        },
      },
    ],
  },

  // Template 7 — Clinic Trust Landing
  {
    id: "clinic-trust",
    name: "Clinic Trust Landing",
    description: "Phòng khám, nha khoa, spa medical — sky blue, trust badges, appointment form.",
    category: "section",
    blocks: [
      {
        type: "menu",
        label: "Clinic Nav",
        props: {
          logoText: "VitaCare Clinic",
          logoUrl: "#",
          items: [
            { label: "Dịch vụ", url: "#services" },
            { label: "Bác sĩ", url: "#doctors" },
            { label: "Đặt lịch", url: "#book" },
            { label: "Liên hệ", url: "#contact" },
          ],
          bgColor: "#ffffff",
          textColor: "#0369a1",
        },
      },
      {
        type: "hero",
        label: "Hero Clinic",
        props: {
          headline: "Chăm sóc sức khỏe tận tâm — Đặt lịch trong 30 giây",
          subheadline: "VitaCare: Phòng khám đa khoa với đội ngũ bác sĩ 15+ năm kinh nghiệm. Được 12.000+ bệnh nhân tin tưởng.",
          ctaText: "Đặt lịch khám ngay",
          ctaUrl: "#book",
          ctaColor: "#0284c7",
          bgColor: "#f0f9ff",
          bgImage: "/images/banners/clinic-trust.png",
          textAlign: "left",
          minHeight: 680,
          overlayOpacity: 0.35,
        },
      },
      {
        type: "collection_list",
        label: "Trust badges",
        props: {
          items: [
            { id: "t1", title: "35 Bác sĩ chuyên khoa", desc: "Đào tạo tại các bệnh viện hàng đầu: BV Bạch Mai, Việt Đức, ĐH Y Hà Nội.", icon: "01" },
            { id: "t2", title: "12.000+ bệnh nhân", desc: "Tỷ lệ hài lòng 96%. Đánh giá trung bình 4.8/5 trên Google.", icon: "02" },
            { id: "t3", title: "ISO 9001:2015", desc: "Chứng nhận quản lý chất lượng quốc tế. Kiểm định định kỳ 6 tháng/lần.", icon: "03" },
          ],
          columns: 3,
          layout: "grid",
          bgColor: "#e0f2fe",
        },
      },
      {
        type: "feature_card",
        label: "Service — Nội khoa",
        props: {
          icon: "♡",
          iconColor: "#0284c7",
          iconBg: "#dbeafe",
          title: "Nội khoa tổng quát",
          description: "Khám và tư vấn toàn diện: tiêu hóa, tim mạch, nội tiết, hô hấp. Kết quả xét nghiệm trong ngày.",
          bgColor: "#ffffff",
          borderColor: "#bae6fd",
          borderRadius: 16,
        },
      },
      {
        type: "feature_card",
        label: "Service — Nha khoa",
        props: {
          icon: "✦",
          iconColor: "#0d9488",
          iconBg: "#ccfbf1",
          title: "Nha khoa thẩm mỹ",
          description: "Trám, bọc sứ, niềng răng trong suốt, tẩy trắng. Máy X-quang kỹ thuật số, không đau.",
          bgColor: "#ffffff",
          borderColor: "#99f6e4",
          borderRadius: 16,
        },
      },
      {
        type: "tabs",
        label: "Booking process",
        props: {
          tabs: [
            { id: "b1", label: "Bước 1", content: "Điền form online hoặc gọi hotline. Chọn chuyên khoa và bác sĩ mong muốn." },
            { id: "b2", label: "Bước 2", content: "Nhận xác nhận lịch hẹn qua SMS và email. Có thể thay đổi lịch trong 24h." },
            { id: "b3", label: "Bước 3", content: "Đến khám đúng giờ. Lấy số ưu tiên tại quầy, thời gian chờ dưới 15 phút." },
          ],
          activeTabId: "b1",
          style: "pills",
          accentColor: "#0284c7",
        },
      },
      {
        type: "testimonial",
        label: "Patient review",
        props: {
          quote: "Lần đầu đặt lịch online, tôi không nghĩ sẽ dễ vậy. Chờ chỉ 10 phút, bác sĩ tận tình giải thích kết quả. Sẽ giới thiệu cho gia đình.",
          authorName: "Ngô Thị Lan Anh",
          authorRole: "Bệnh nhân — Khoa Nội tiết",
          authorAvatar: "",
          rating: 5,
          bgColor: "#f0f9ff",
          textColor: "#0c4a6e",
          showRating: true,
        },
      },
      {
        type: "accordion",
        label: "Clinic FAQ",
        props: {
          items: [
            { id: "q1", question: "Có cần mang hồ sơ cũ không?", answer: "Nên mang hồ sơ nếu có để bác sĩ có thể đánh giá toàn diện. Nếu không có, phòng khám sẽ tạo hồ sơ mới miễn phí." },
            { id: "q2", question: "Bảo hiểm y tế có được sử dụng không?", answer: "Phòng khám tiếp nhận BHYT và đại lý bảo hiểm tư nhân. Vui lòng xuất trình thẻ khi check-in." },
          ],
          allowMultiple: false,
          accentColor: "#0284c7",
        },
      },
      {
        type: "collection_list",
        label: "Clinic trust stats",
        props: {
          items: [
            { id: "c1", title: "15 năm", desc: "Kinh nghiệm thăm khám & điều trị", icon: "01" },
            { id: "c2", title: "28,000+", desc: "Bệnh nhân đã điều trị thành công", icon: "02" },
            { id: "c3", title: "12 bác sĩ", desc: "Chuyên gia đầu ngành, chứng chỉ Quốc tế", icon: "03" },
            { id: "c4", title: "4.9 / 5", desc: "Đánh giá của bệnh nhân trên Google", icon: "04" },
          ],
          columns: 4,
          layout: "grid",
          bgColor: "#e0f2fe",
        },
      },
      {
        type: "testimonial",
        label: "Patient review",
        props: {
          quote: "Tôi đã chờ đợi rất lâu để tìm được phòng khám như thế này. Bác sĩ tận tâm, giải thích rõ ràng, không vội vàng. Điều trị dứt điểm sau 2 tháng.",
          authorName: "Nguyễn Thị Hương",
          authorRole: "Bệnh nhân — Điều trị viêm khớp mãn tính tại VitaCare",
          authorAvatar: "",
          rating: 5,
          bgColor: "#f0f9ff",
          textColor: "#0c4a6e",
          showRating: true,
        },
      },
      {
        type: "form_capture",
        label: "Appointment form",
        props: {
          title: "Đặt lịch khám — Nhanh & Dễ",
          subtitle: "Điền form, chúng tôi xác nhận trong 15 phút.",
          fields: [
            { id: "name", label: "Họ và tên bệnh nhân", type: "text", required: true },
            { id: "phone", label: "Số điện thoại", type: "phone", required: true },
            { id: "specialty", label: "Chuyên khoa cần khám", type: "text", required: false },
          ],
          submitLabel: "Đặt lịch ngay",
          submitColor: "#0284c7",
          bgColor: "#ffffff",
          borderRadius: 16,
        },
      },
    ],
  },

  // Template 8 — Restaurant Premium Menu
  {
    id: "restaurant-menu",
    name: "Restaurant Premium Menu",
    description: "Nhà hàng, quán cafe — warm cream/wine, food gallery, reservation form.",
    category: "section",
    blocks: [
      {
        type: "hero",
        label: "Hero Restaurant",
        props: {
          headline: "Hương vị chuẩn Á — Không gian tối giản tinh tế",
          subheadline: "Nhà hàng Umami — Ẩm thực fusion Nhật-Việt. Đặt bàn trước để có chỗ ngồi tốt nhất.",
          ctaText: "Đặt bàn ngay",
          ctaUrl: "#reserve",
          ctaColor: "#fbbf24",
          bgColor: "#1a0800",
          bgImage: "/images/grid-image/image-02.png",
          textAlign: "left",
          minHeight: 720,
          overlayOpacity: 0.55,
        },
      },
      {
        type: "tabs",
        label: "Menu categories",
        props: {
          tabs: [
            { id: "starters", label: "Khai vị", content: "Gỏi xoài tôm thịt 85k · Chả giò tôm hùm 120k · Súp miso cá hồi 75k · Sashimi Umami 185k" },
            { id: "mains", label: "Món chính", content: "Ramen tonkotsu 195k · Bò Wagyu teppan 485k · Cơm chiên hải sản 165k · Cá hồi teriyaki 245k" },
            { id: "desserts", label: "Tráng miệng", content: "Bánh mochi kem matcha 85k · Chè đậu đỏ 65k · Creme brûlée 95k · Mochi ice cream 3 vị 110k" },
          ],
          activeTabId: "starters",
          style: "underline",
          accentColor: "#d97706",
        },
      },
      {
        type: "gallery",
        label: "Food gallery",
        props: {
          images: [
            "/images/grid-image/image-01.png",
            "/images/grid-image/image-03.png",
            "/images/grid-image/image-04.png",
            "/images/grid-image/image-05.png",
            "/images/grid-image/image-06.png",
          ],
          columns: 3,
          gap: 10,
          borderRadius: 10,
          aspectRatio: "4/3",
        },
      },
      {
        type: "text",
        label: "Restaurant story",
        props: {
          content: "Umami được thành lập năm 2019 bởi bếp trưởng Kenji Tanaka — người đã dành 12 năm học nghề tại Kyoto và Tokyo trước khi mang triết lý ẩm thực 'ít nhưng tinh' đến Hà Nội. Mỗi món ăn là sự giao thoa giữa kỹ thuật Nhật và nguyên liệu Việt tươi hàng ngày.",
          fontSize: 18,
          color: "#44403c",
          textAlign: "center",
          lineHeight: 1.9,
          paddingX: 64,
          paddingY: 48,
        },
      },
      {
        type: "testimonial",
        label: "Diner review",
        props: {
          quote: "Ramen tonkotsu ngon nhất Hà Nội tôi từng ăn. Nước dùng hầm 18 tiếng, không gian yên tĩnh, nhân viên ân cần. Đây là nơi tôi đưa khách nước ngoài mỗi lần.",
          authorName: "David Nguyen",
          authorRole: "Food blogger — Saigon & Hanoi Eats",
          authorAvatar: "",
          rating: 5,
          bgColor: "#fef3c7",
          textColor: "#1c1917",
          showRating: true,
        },
      },
      {
        type: "collection_list",
        label: "Restaurant stats",
        props: {
          items: [
            { id: "r1", title: "12 năm", desc: "Kinh nghiệm ẩm thực Nhật–Việt", icon: "01" },
            { id: "r2", title: "4.8 / 5", desc: "Google Reviews (1,200+ đánh giá)", icon: "02" },
            { id: "r3", title: "Top 10", desc: "Best Restaurant HCM 2024 — Foody", icon: "03" },
            { id: "r4", title: "3 chi nhánh", desc: "Q1, Q3 & Bình Thạnh", icon: "04" },
          ],
          columns: 4,
          layout: "grid",
          bgColor: "#2c1400",
        },
      },
      {
        type: "testimonial",
        label: "Diner review",
        props: {
          quote: "Tôi đã ăn Umami từ khi mới khai trương. Tộ rươu nướng của họ là thứ tôi nghĩ đến mỗi khi buồn. Không đâu có nước dùng ngon hơn.",
          authorName: "Lê Thúy Anh",
          authorRole: "Food Blogger — 100K followers — Hà Nội",
          authorAvatar: "",
          rating: 5,
          bgColor: "#1a0800",
          textColor: "#fbbf24",
          showRating: true,
        },
      },
      {
        type: "form_capture",
        label: "Reservation form",
        props: {
          title: "Đặt bàn — Hôm nay hoặc cuối tuần",
          subtitle: "Gửi yêu cầu, chúng tôi xác nhận trong 30 phút qua Zalo/điện thoại.",
          fields: [
            { id: "name", label: "Tên khách đặt bàn", type: "text", required: true },
            { id: "phone", label: "Số điện thoại Zalo", type: "phone", required: true },
            { id: "guests", label: "Số lượng khách", type: "text", required: true },
            { id: "time", label: "Ngày & giờ mong muốn", type: "text", required: true },
          ],
          submitLabel: "Đặt bàn ngay",
          submitColor: "#d97706",
          bgColor: "#fffbeb",
          borderRadius: 12,
        },
      },
    ],
  },

  // Template 9 — Mobile App Launch
  {
    id: "mobile-app",
    name: "Mobile App Launch",
    description: "App fintech/productivity — teal gradient, feature tabs, download CTA.",
    category: "section",
    blocks: [
      {
        type: "hero",
        label: "Hero App Launch",
        props: {
          headline: "Your money, organized — finally.",
          subheadline: "Pendo tracks every expense, splits bills, forecasts your savings and alerts you before you overspend. Free forever.",
          ctaText: "Download on App Store",
          ctaUrl: "#download",
          ctaColor: "#0f766e",
          bgColor: "#0d9488",
          bgImage: "/images/banners/mobile-app.png",
          textAlign: "center",
          minHeight: 720,
          overlayOpacity: 0.45,
        },
      },
      {
        type: "collection_list",
        label: "App benefits",
        props: {
          items: [
            { id: "b1", title: "Auto-categorize", desc: "AI tự động phân loại chi tiêu. Không cần nhập tay.", icon: "01" },
            { id: "b2", title: "Split bills", desc: "Chia tiền bạn bè dễ dàng — Momo, bank transfer.", icon: "02" },
            { id: "b3", title: "Smart alerts", desc: "Cảnh báo khi chi tiêu vượt budget hoặc có giao dịch lạ.", icon: "03" },
          ],
          columns: 3,
          layout: "grid",
          bgColor: "#0d9488",
        },
      },
      {
        type: "tabs",
        label: "App feature screenshots",
        props: {
          tabs: [
            { id: "dash", label: "Dashboard", content: "Tổng quan chi tiêu tháng, biểu đồ danh mục, số dư ví và tài khoản ngân hàng liên kết — tất cả trên 1 màn hình." },
            { id: "split", label: "Bill Split", content: "Chụp hóa đơn, AI đọc và đề xuất chia tiền. Gửi nhắc nhở tự động qua Zalo/messenger." },
            { id: "save", label: "Savings", content: "Đặt mục tiêu tiết kiệm: du lịch, học phí, mua nhà. AI lên kế hoạch hàng tháng phù hợp thu nhập." },
          ],
          activeTabId: "dash",
          style: "pills",
          accentColor: "#0f766e",
        },
      },
      {
        type: "feature_card",
        label: "Security badge",
        props: {
          icon: "🔐",
          iconColor: "#0f766e",
          iconBg: "#ccfbf1",
          title: "Bank-grade security",
          description: "256-bit encryption. Read-only access to bank data — we never store your credentials. ISO 27001 certified.",
          bgColor: "#f0fdfa",
          borderColor: "#99f6e4",
          borderRadius: 16,
        },
      },
      {
        type: "testimonial",
        label: "App review",
        props: {
          quote: "Tôi đã thử 6 app quản lý chi tiêu nhưng đây là app duy nhất tôi dùng được hơn 3 tháng. Giao diện cực sạch, không rác.",
          authorName: "Trần Quốc Bảo",
          authorRole: "⭐⭐⭐⭐⭐ App Store Review",
          authorAvatar: "",
          rating: 5,
          bgColor: "#f0fdfa",
          textColor: "#134e4a",
          showRating: true,
        },
      },
      {
        type: "collection_list",
        label: "App download stats",
        props: {
          items: [
            { id: "a1", title: "2.1M+", desc: "Downloads on iOS & Android", icon: "01" },
            { id: "a2", title: "4.8 / 5", desc: "App Store & Google Play rating", icon: "02" },
            { id: "a3", title: "$840M", desc: "Tracked by users in last 12 months", icon: "03" },
            { id: "a4", title: "Bank-grade", desc: "256-bit encryption, SOC 2 certified", icon: "04" },
          ],
          columns: 4,
          layout: "grid",
          bgColor: "#0f766e",
        },
      },
      {
        type: "testimonial",
        label: "App user review",
        props: {
          quote: "Pendo literally saved me from overdrafting 3 times last month. The alerts are scary accurate. I’ve recommended it to everyone in my friend group.",
          authorName: "Jasmine R.",
          authorRole: "Freelance Designer — Los Angeles",
          authorAvatar: "",
          rating: 5,
          bgColor: "#0d9488",
          textColor: "#ffffff",
          showRating: true,
        },
      },
      {
        type: "form_capture",
        label: "Early access form",
        props: {
          title: "Get early access — Limited beta spots",
          subtitle: "Join 4,200 beta users. We'll send download link the day you're approved.",
          fields: [
            { id: "email", label: "Email address", type: "email", required: true },
            { id: "phone", label: "Phone number (for SMS)", type: "phone", required: false },
          ],
          submitLabel: "Request early access →",
          submitColor: "#0f766e",
          bgColor: "#ffffff",
          borderRadius: 14,
        },
      },
    ],
  },

  // Template 10 — Finance Lead Generation
  {
    id: "finance-lead",
    name: "Finance Lead Generation",
    description: "Bảo hiểm, tư vấn đầu tư, kế toán — navy sẫm, trust indicators, lead form.",
    category: "section",
    blocks: [
      {
        type: "menu",
        label: "Finance Nav",
        props: {
          logoText: "ProsperWealth",
          logoUrl: "#",
          items: [
            { label: "Dịch vụ", url: "#services" },
            { label: "Quy trình", url: "#process" },
            { label: "FAQ", url: "#faq" },
            { label: "Tư vấn ngay", url: "#lead" },
          ],
          bgColor: "#0c2340",
          textColor: "#34d399",
        },
      },
      {
        type: "hero",
        label: "Hero Finance",
        props: {
          headline: "Tài sản của bạn xứng đáng được quản lý chuyên nghiệp hơn",
          subheadline: "ProsperWealth — tư vấn tài chính độc lập, không hoa hồng ẩn. Hơn 850 gia đình đã lập kế hoạch bảo vệ tài sản cùng chúng tôi.",
          ctaText: "Nhận tư vấn miễn phí 30 phút",
          ctaUrl: "#lead",
          ctaColor: "#34d399",
          bgColor: "#0c2340",
          bgImage: "/images/banners/finance-lead.png",
          textAlign: "left",
          minHeight: 700,
          overlayOpacity: 0.65,
        },
      },
      {
        type: "collection_list",
        label: "Trust indicators",
        props: {
          items: [
            { id: "t1", title: "850+ gia đình tin tưởng", desc: "Tỷ lệ gia hạn hợp đồng 91%. Khách hàng trung bình đã làm việc với chúng tôi 6 năm.", icon: "01" },
            { id: "t2", title: "Chứng chỉ CFP & CFA", desc: "Toàn bộ chuyên viên đạt chuẩn Certified Financial Planner hoặc CFA Level 2+.", icon: "02" },
            { id: "t3", title: "Minh bạch 100% phí", desc: "Chỉ thu phí tư vấn cố định. Không hoa hồng sản phẩm, không xung đột lợi ích.", icon: "03" },
          ],
          columns: 3,
          layout: "grid",
          bgColor: "#0a1f38",
        },
      },
      {
        type: "tabs",
        label: "Service types",
        props: {
          tabs: [
            { id: "personal", label: "Cá nhân & Gia đình", content: "Lập ngân sách, kế hoạch nghỉ hưu sớm (FIRE), bảo hiểm nhân thọ/sức khỏe, đầu tư dài hạn." },
            { id: "business", label: "Doanh nghiệp SME", content: "Kế hoạch thuế, quản lý dòng tiền, quỹ lương thưởng, bảo hiểm nhóm." },
            { id: "invest", label: "Đầu tư & Tài sản", content: "Phân bổ danh mục cổ phiếu/ETF/bất động sản. Tái cân bằng định kỳ theo mục tiêu." },
          ],
          activeTabId: "personal",
          style: "pills",
          accentColor: "#34d399",
        },
      },
      {
        type: "table",
        label: "4-step process",
        props: {
          headers: ["Bước", "Nội dung", "Thời gian"],
          rows: [
            ["01 — Discovery", "Phiên 30 phút miễn phí: tìm hiểu tình hình tài chính hiện tại", "30 phút"],
            ["02 — Analysis", "Phân tích gap, rủi ro và cơ hội dựa trên data thực tế", "1 tuần"],
            ["03 — Plan", "Lập kế hoạch tài chính 3-5 năm, trình bày báo cáo PDF", "3 ngày"],
            ["04 — Execute", "Đồng hành triển khai, review hàng quý", "Ongoing"],
          ],
          bgColor: "#ffffff",
          borderColor: "#e2e8f0",
        },
      },
      {
        type: "testimonial",
        label: "Client story",
        props: {
          quote: "Sau 2 năm làm việc với ProsperWealth, tôi không chỉ biết mình có bao nhiêu tiền mà biết chính xác mình đang tiến về đâu. Lần đầu tiên tôi thực sự thấy an tâm về tương lai.",
          authorName: "Vũ Tiến Đạt",
          authorRole: "Giám đốc kinh doanh — Khách hàng từ 2022",
          authorAvatar: "",
          rating: 5,
          bgColor: "#0a1f38",
          textColor: "#e2e8f0",
          showRating: true,
        },
      },
      {
        type: "accordion",
        label: "Finance FAQ",
        props: {
          items: [
            { id: "q1", question: "Chi phí tư vấn là bao nhiêu?", answer: "Phiên Discovery miễn phí. Kế hoạch tài chính đầy đủ từ 3.500.000đ. Gói theo dõi hàng năm từ 5.000.000đ. Không phí ẩn." },
            { id: "q2", question: "Tôi cần chuẩn bị gì trước buổi tư vấn?", answer: "Chỉ cần biết sơ lược thu nhập, các khoản vay hiện tại và mục tiêu muốn đạt được. Chúng tôi sẽ hỏi phần còn lại." },
          ],
          allowMultiple: false,
          accentColor: "#34d399",
        },
      },
      {
        type: "collection_list",
        label: "Finance credibility",
        props: {
          items: [
            { id: "f1", title: "850+", desc: "Gia đình đã lập kế hoạch tài chính", icon: "01" },
            { id: "f2", title: "12 năm", desc: "Kinh nghiệm tư vấn đầu tư & bảo hiểm", icon: "02" },
            { id: "f3", title: "CFP & CFA", desc: "Chứng chỉ quốc tế của đội ngũ cố vấn", icon: "03" },
            { id: "f4", title: "Không hoa hồng", desc: "Tư vấn độc lập, không bán sản phẩm tài chính", icon: "04" },
          ],
          columns: 4,
          layout: "grid",
          bgColor: "#0a1929",
        },
      },
      {
        type: "testimonial",
        label: "Client success story",
        props: {
          quote: "ProsperWealth giúp tôi dừng được việc phân tán tài sản vô định hướng. Sau 6 tháng có kế hoạch rõ ràng, tôi ngủ ngon hơn hẳn.",
          authorName: "Phạm Thành Đạt",
          authorRole: "Giám đốc kinh doanh — 45 tuổi — Hà Nội",
          authorAvatar: "",
          rating: 5,
          bgColor: "#0c2340",
          textColor: "#34d399",
          showRating: true,
        },
      },
      {
        type: "form_capture",
        label: "Finance lead form",
        props: {
          title: "Đăng ký phiên tư vấn 30 phút — Miễn phí",
          subtitle: "Chuyên viên sẽ liên hệ xác nhận lịch trong 4 giờ làm việc.",
          fields: [
            { id: "name", label: "Họ và tên", type: "text", required: true },
            { id: "phone", label: "Số điện thoại", type: "phone", required: true },
            { id: "goal", label: "Mục tiêu tài chính ưu tiên", type: "text", required: false },
          ],
          submitLabel: "Đặt lịch tư vấn miễn phí",
          submitColor: "#34d399",
          bgColor: "#0c2340",
          borderRadius: 14,
        },
      },
    ],
  },

  // Template 11 — Beauty Spa Elegant
  {
    id: "beauty-spa",
    name: "Beauty Spa Elegant",
    description: "Spa, thẩm mỹ viện, salon — silk pink, feminine elegant, booking form.",
    category: "section",
    blocks: [
      {
        type: "menu",
        label: "Spa Nav",
        props: {
          logoText: "Lumière Spa",
          logoUrl: "#",
          items: [
            { label: "Dịch vụ", url: "#services" },
            { label: "Chuyên gia", url: "#team" },
            { label: "Ưu đãi", url: "#offers" },
            { label: "Đặt lịch", url: "#book" },
          ],
          bgColor: "#fdf2f8",
          textColor: "#be185d",
        },
      },
      {
        type: "hero",
        label: "Hero Spa",
        props: {
          headline: "Vẻ đẹp tỏa sáng từ bên trong",
          subheadline: "Lumière Spa — liệu trình chăm sóc da và toàn thân cao cấp. Kết hợp công nghệ châu Âu và nguyên liệu thảo mộc Việt Nam.",
          ctaText: "Đặt lịch thư giãn ngay",
          ctaUrl: "#book",
          ctaColor: "#be185d",
          bgColor: "#fdf2f8",
          bgImage: "/images/banners/beauty-spa.png",
          textAlign: "center",
          minHeight: 700,
          overlayOpacity: 0.2,
        },
      },
      {
        type: "tabs",
        label: "Service packages",
        props: {
          tabs: [
            { id: "face", label: "Chăm sóc da mặt", content: "Facial cơ bản 350k · Điều trị mụn chuyên sâu 780k · Trẻ hóa da RF 1.200k · Peel da tế bào chết 650k" },
            { id: "body", label: "Toàn thân", content: "Massage thư giãn 60ph 450k · Hot stone massage 650k · Body wrap tảo biển 850k · Scrub muối Himalaya 550k" },
            { id: "combo", label: "Combo tiết kiệm", content: "Beauty Escape (facial + body 2h30) 1.150k · Weekend Retreat (full day) 2.200k · Monthly Care 4 buổi facial 2.500k" },
          ],
          activeTabId: "face",
          style: "underline",
          accentColor: "#be185d",
        },
      },
      {
        type: "collection_list",
        label: "Expert team",
        props: {
          items: [
            { id: "e1", title: "Nguyễn Hà Linh", desc: "Chuyên gia da liễu 8 năm. Đào tạo tại Paris & Seoul.", icon: "01" },
            { id: "e2", title: "Trần Kim Oanh", desc: "Master therapist. Chứng chỉ CIDESCO quốc tế.", icon: "02" },
            { id: "e3", title: "Lê Phương Chi", desc: "Nail & brow specialist. 600+ khách hàng trung thành.", icon: "03" },
          ],
          columns: 3,
          layout: "grid",
          bgColor: "#fce7f3",
        },
      },
      {
        type: "feature_card",
        label: "Monthly promotion",
        props: {
          icon: "✿",
          iconColor: "#be185d",
          iconBg: "#fce7f3",
          title: "Ưu đãi tháng 6 — Giảm 30%",
          description: "Đặt lịch từ thứ 2-5, giảm ngay 30% cho toàn bộ liệu trình facial và combo. Áp dụng đến hết 30/06.",
          bgColor: "#fff1f2",
          borderColor: "#fecdd3",
          borderRadius: 20,
        },
      },
      {
        type: "testimonial",
        label: "Spa review",
        props: {
          quote: "Da tôi đã cải thiện rõ rệt sau 4 buổi facial. Không gian yên tĩnh như một ốc đảo giữa thành phố. Đây là nơi tôi 'sạc pin' mỗi tháng.",
          authorName: "Minh Châu",
          authorRole: "Khách hàng thân thiết — 2 năm",
          authorAvatar: "",
          rating: 5,
          bgColor: "#fff1f2",
          textColor: "#881337",
          showRating: true,
        },
      },
      {
        type: "accordion",
        label: "Spa FAQ",
        props: {
          items: [
            { id: "q1", question: "Lần đầu đến cần chuẩn bị gì?", answer: "Không cần chuẩn bị gì đặc biệt. Đến sớm 10 phút để điền phiếu đánh giá da và thư giãn trước khi vào phòng điều trị." },
            { id: "q2", question: "Có thể đặt nhóm (hen girls day) không?", answer: "Có! Nhóm từ 3 người trở lên được giảm thêm 10% và có phòng VIP riêng. Gọi hotline để sắp xếp." },
          ],
          allowMultiple: false,
          accentColor: "#be185d",
        },
      },
      {
        type: "collection_list",
        label: "Spa credentials",
        props: {
          items: [
            { id: "s1", title: "8 năm", desc: "Thương hiệu spa hàng đầu miền Bắc", icon: "01" },
            { id: "s2", title: "15,000+", desc: "Khách hàng thường xuyên", icon: "02" },
            { id: "s3", title: "20+ liệu pháp", desc: "Từ châu Âu và Đông Nam Á", icon: "03" },
            { id: "s4", title: "4.9 / 5", desc: "Trung bình trên Foody & Google", icon: "04" },
          ],
          columns: 4,
          layout: "grid",
          bgColor: "#fce7f3",
        },
      },
      {
        type: "testimonial",
        label: "Spa guest review",
        props: {
          quote: "Lumière là nơi tôi cảm thấy thực sự được chăm sóc từ đầu đến cuối. Ánh đèn, mùi hương, bàn tay của chuyên viên — tất cả đều ở đẳng cấp khác hẳn.",
          authorName: "Quỳnh Anh",
          authorRole: "Beauty Content Creator — 200K followers",
          authorAvatar: "",
          rating: 5,
          bgColor: "#fdf2f8",
          textColor: "#831843",
          showRating: true,
        },
      },
      {
        type: "form_capture",
        label: "Spa booking form",
        props: {
          title: "Đặt lịch — Chỉ mất 1 phút",
          subtitle: "Chúng tôi xác nhận qua Zalo trong 15 phút. Hủy lịch miễn phí trước 24h.",
          fields: [
            { id: "name", label: "Tên của bạn", type: "text", required: true },
            { id: "phone", label: "Số Zalo", type: "phone", required: true },
            { id: "service", label: "Dịch vụ quan tâm", type: "text", required: false },
          ],
          submitLabel: "Đặt lịch ngay ✿",
          submitColor: "#be185d",
          bgColor: "#fdf2f8",
          borderRadius: 20,
        },
      },
    ],
  },

  // Template 12 — Local Service Lead Gen
  {
    id: "local-service",
    name: "Local Service Lead Gen",
    description: "Sửa điện lạnh, vệ sinh nhà, lắp camera — cam đậm, phone CTA, price table.",
    category: "section",
    blocks: [
      {
        type: "hero",
        label: "Hero Local Service",
        props: {
          headline: "Sửa điều hòa — Gọi là có ngay, bảo hành 12 tháng",
          subheadline: "AirFix — Dịch vụ sửa, vệ sinh điều hòa tại nhà. Thợ lành nghề, phụ tùng chính hãng, báo giá minh bạch trước khi làm.",
          ctaText: "📞 Gọi ngay: 0901-XXX-XXX",
          ctaUrl: "tel:+84901000000",
          ctaColor: "#ea580c",
          bgColor: "#fff7ed",
          bgImage: "/images/banners/local-service.png",
          textAlign: "left",
          minHeight: 640,
          overlayOpacity: 0.3,
        },
      },
      {
        type: "collection_list",
        label: "Service list",
        props: {
          items: [
            { id: "s1", title: "Vệ sinh điều hòa", desc: "Tháo lắp, rửa dàn lạnh, diệt khuẩn khử mùi. Thời gian: 60-90 phút.", icon: "01" },
            { id: "s2", title: "Sửa chữa hư hỏng", desc: "Thay gas, sửa board mạch, quạt, bơm. Bảo hành linh kiện 12 tháng.", icon: "02" },
            { id: "s3", title: "Lắp đặt mới", desc: "Lắp tất cả hãng: Daikin, Mitsubishi, LG, Panasonic. Cam kết đúng kỹ thuật.", icon: "03" },
          ],
          columns: 3,
          layout: "grid",
          bgColor: "#ea580c",
        },
      },
      {
        type: "feature_card",
        label: "Why choose AirFix",
        props: {
          icon: "✓",
          iconColor: "#ea580c",
          iconBg: "#fff7ed",
          title: "Cam kết 5 không",
          description: "Không phát sinh · Không ép giá · Không gây hư hỏng thêm · Không dùng phụ tùng không rõ nguồn gốc · Không thanh toán nếu không hài lòng.",
          bgColor: "#ffffff",
          borderColor: "#fed7aa",
          borderRadius: 14,
        },
      },
      {
        type: "table",
        label: "Price table",
        props: {
          headers: ["Dịch vụ", "Đơn giá", "Ghi chú"],
          rows: [
            ["Vệ sinh 1 chiều", "200.000đ", "Bao gồm diệt khuẩn"],
            ["Vệ sinh 2 chiều", "320.000đ", "Bao gồm rửa dàn nóng"],
            ["Bơm gas R32/R410a", "350.000đ", "Bao gồm gas + công"],
            ["Sửa board mạch", "Từ 450.000đ", "Tùy bo mạch, báo giá trước"],
            ["Lắp điều hòa mới", "Từ 500.000đ", "Bao gồm đấu dây, đục tường"],
          ],
          bgColor: "#ffffff",
          borderColor: "#e5e7eb",
        },
      },
      {
        type: "collection_list",
        label: "Service area",
        props: {
          items: [
            { id: "a1", title: "Hà Nội nội thành", desc: "Ba Đình, Đống Đa, Cầu Giấy, Hoàn Kiếm, Hai Bà Trưng, Thanh Xuân, Nam Từ Liêm.", icon: "01" },
            { id: "a2", title: "Hà Nội ngoại thành", desc: "Hà Đông, Long Biên, Hoàng Mai, Bắc Từ Liêm, Gia Lâm. Thêm phí 30k/5km.", icon: "02" },
            { id: "a3", title: "Thời gian phục vụ", desc: "7:00–20:00 hàng ngày, kể cả Chủ nhật. Ca khẩn cấp thêm phụ phí 50k.", icon: "03" },
          ],
          columns: 3,
          layout: "grid",
          bgColor: "#fff7ed",
        },
      },
      {
        type: "testimonial",
        label: "Local review",
        props: {
          quote: "Điều hòa nhà tôi bị chảy nước, gọi lúc 8 giờ sáng, 9 giờ thợ đã đến. Sửa xong trong 1 tiếng, thợ lịch sự, dọn dẹp sạch sẽ. Giá đúng như báo trước, không phát sinh.",
          authorName: "Chị Ngọc Ánh",
          authorRole: "Khách hàng tại Cầu Giấy, Hà Nội",
          authorAvatar: "",
          rating: 5,
          bgColor: "#fff7ed",
          textColor: "#7c2d12",
          showRating: true,
        },
      },
      {
        type: "collection_list",
        label: "Service trust stats",
        props: {
          items: [
            { id: "l1", title: "9 năm", desc: "Chuyên sửa điều hòa tại Hà Nội", icon: "01" },
            { id: "l2", title: "25,000+", desc: "Cuộc gọi xử lý thành công", icon: "02" },
            { id: "l3", title: "2 giờ", desc: "Phản hồi kỹ thuật tỹ lệ 90%+ trong giờ", icon: "03" },
            { id: "l4", title: "Bảo hành 12T", desc: "Lịnh kiện chính hãng, không phít loanh", icon: "04" },
          ],
          columns: 4,
          layout: "grid",
          bgColor: "#fff3e0",
        },
      },
      {
        type: "testimonial",
        label: "Customer review local",
        props: {
          quote: "Gọi lúc 9 giờ sáng, thợ đến lúc 10h30 đã sửa xong. Báo giá trước, không phát sinh. Điều hòa chạy mát ngon từ đó đến giờ — 3 năm rồi đấy.",
          authorName: "Bà Nguyễn Lan Hương",
          authorRole: "Khách hàng — Cầu Giấy, Hà Nội",
          authorAvatar: "",
          rating: 5,
          bgColor: "#fff7ed",
          textColor: "#7c2d12",
          showRating: true,
        },
      },
      {
        type: "form_capture",
        label: "Local lead form",
        props: {
          title: "Đặt lịch — Nhận báo giá trong 5 phút",
          subtitle: "Mô tả sơ qua vấn đề, thợ sẽ báo giá trước khi đến. Không phát sinh.",
          fields: [
            { id: "name", label: "Họ và tên", type: "text", required: true },
            { id: "phone", label: "Số điện thoại", type: "phone", required: true },
            { id: "address", label: "Địa chỉ (quận/phường)", type: "text", required: true },
            { id: "issue", label: "Mô tả hư hỏng", type: "text", required: false },
          ],
          submitLabel: "Đặt lịch ngay — Báo giá miễn phí",
          submitColor: "#ea580c",
          bgColor: "#ffffff",
          borderRadius: 12,
        },
      },
    ],
  },
];

